import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={inter.className}>
        <div>
          <div className="flex justify-evenly max-w-7xl mx-auto p-2 rounded-md bg-lime-200 mt-5">
            <Link href={"/users"} className="text-gray-950 px-3 py-1 rounded-md bg-lime-100 shadow-lg">کاربران</Link>
            <Link href={"/albums"} className="text-gray-950 px-3 py-1 rounded-md bg-lime-100 shadow-lg">البوم ها</Link>
            <Link href={"/todo"} className="text-gray-950 px-3 py-1 rounded-md bg-lime-100 shadow-lg">دفترچه یادداشت</Link>
            <Link href={"/landing"} className="text-gray-950 px-3 py-1 rounded-md bg-lime-100 shadow-lg">لندینگ پیج</Link>
            <Link href={"/landing2"} className="text-gray-950 px-3 py-1 rounded-md bg-lime-100 shadow-lg">not found</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
